"""Descripción de los cambios

Revision ID: 3fd6f2af670d
Revises: 70b588154144
Create Date: 2025-03-20 01:56:57.276909

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3fd6f2af670d'
down_revision: Union[str, None] = '70b588154144'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('viajes_vehiculo_id_fkey', 'viajes', type_='foreignkey')
    op.drop_constraint('documentos_vehiculo_vehiculo_id_fkey', 'documentos_vehiculo', type_='foreignkey')

    op.drop_index('ix_vehiculos_codigo', table_name='vehiculos')
    op.drop_index('ix_vehiculos_id', table_name='vehiculos')
    op.drop_index('ix_vehiculos_marca', table_name='vehiculos')
    op.drop_index('ix_vehiculos_modelo', table_name='vehiculos')
    op.drop_index('ix_vehiculos_patente', table_name='vehiculos')
    op.drop_table('vehiculos')
    op.drop_index('ix_users_email', table_name='users')
    op.drop_index('ix_users_id', table_name='users')
    op.drop_index('ix_users_username', table_name='users')
    op.drop_table('users')
    op.drop_index('ix_documentos_viajes_archivo_url', table_name='documentos_viajes')
    op.drop_index('ix_documentos_viajes_codigo', table_name='documentos_viajes')
    op.drop_index('ix_documentos_viajes_codigo_documento', table_name='documentos_viajes')
    op.drop_index('ix_documentos_viajes_id', table_name='documentos_viajes')
    op.drop_index('ix_documentos_viajes_tipo_documento', table_name='documentos_viajes')
    op.drop_table('documentos_viajes')
    op.drop_index('ix_documentos_conductores_id', table_name='documentos_conductores')
    op.drop_table('documentos_conductores')
    op.drop_index('ix_documentos_vehiculo_codigo', table_name='documentos_vehiculo')
    op.drop_index('ix_documentos_vehiculo_id', table_name='documentos_vehiculo')
    op.drop_index('ix_documentos_vehiculo_tipo_documento', table_name='documentos_vehiculo')
    op.drop_table('documentos_vehiculo')
    op.drop_index('ix_conductores_id', table_name='conductores')
    op.drop_table('conductores')
    op.drop_index('ix_viajes_id', table_name='viajes')
    op.drop_table('viajes')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('viajes',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('viajes_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('codigo', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('origen', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('destino', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('vehiculo_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('fecha_salida', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('fecha_llegada', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('producto', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('precio', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('peso', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('estado', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('fecha_creacion', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('fecha_actualizacion', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['vehiculo_id'], ['vehiculos.id'], name='viajes_vehiculo_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='viajes_pkey'),
    sa.UniqueConstraint('codigo', name='viajes_codigo_key'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_viajes_id', 'viajes', ['id'], unique=False)
    op.create_table('conductores',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('conductores_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('codigo', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('nombre', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('apellido', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('foto', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('dni', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('numero_contacto', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('email_contacto', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('direccion', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('estado', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('creado_en', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('actualizado_en', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='conductores_pkey'),
    sa.UniqueConstraint('codigo', name='conductores_codigo_key'),
    sa.UniqueConstraint('dni', name='conductores_dni_key'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_conductores_id', 'conductores', ['id'], unique=False)
    op.create_table('documentos_vehiculo',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('codigo', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('vehiculo_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('tipo_documento', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('fecha_emision', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('fecha_vencimiento', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('archivo_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('fecha_carga', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('fecha_actualizacion', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['vehiculo_id'], ['vehiculos.id'], name='documentos_vehiculo_vehiculo_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='documentos_vehiculo_pkey')
    )
    op.create_index('ix_documentos_vehiculo_tipo_documento', 'documentos_vehiculo', ['tipo_documento'], unique=False)
    op.create_index('ix_documentos_vehiculo_id', 'documentos_vehiculo', ['id'], unique=False)
    op.create_index('ix_documentos_vehiculo_codigo', 'documentos_vehiculo', ['codigo'], unique=False)
    op.create_table('documentos_conductores',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('codigo', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('id_conductor', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('tipo_documento', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('archivo_url', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('fecha_emision', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('fecha_vencimiento', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('fecha_carga', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('actualizado_en', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id_conductor'], ['conductores.id'], name='documentos_conductores_id_conductor_fkey'),
    sa.PrimaryKeyConstraint('id', name='documentos_conductores_pkey')
    )
    op.create_index('ix_documentos_conductores_id', 'documentos_conductores', ['id'], unique=False)
    op.create_table('documentos_viajes',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('codigo', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('viaje_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('tipo_documento', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('codigo_documento', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('fecha_emision', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('fecha_vencimiento', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('archivo_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('fecha_creacion', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['viaje_id'], ['viajes.id'], name='documentos_viajes_viaje_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='documentos_viajes_pkey')
    )
    op.create_index('ix_documentos_viajes_tipo_documento', 'documentos_viajes', ['tipo_documento'], unique=False)
    op.create_index('ix_documentos_viajes_id', 'documentos_viajes', ['id'], unique=False)
    op.create_index('ix_documentos_viajes_codigo_documento', 'documentos_viajes', ['codigo_documento'], unique=False)
    op.create_index('ix_documentos_viajes_codigo', 'documentos_viajes', ['codigo'], unique=False)
    op.create_index('ix_documentos_viajes_archivo_url', 'documentos_viajes', ['archivo_url'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('hashed_password', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('role', postgresql.ENUM('ADMINISTRADOR', 'CONDUCTOR', name='userrole'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='users_pkey')
    )
    op.create_index('ix_users_username', 'users', ['username'], unique=True)
    op.create_index('ix_users_id', 'users', ['id'], unique=False)
    op.create_index('ix_users_email', 'users', ['email'], unique=True)
    op.create_table('vehiculos',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('codigo', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('marca', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('modelo', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('patente', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('anio', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('tipo', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('tara', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('carga_maxima', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('estado', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('fecha_alta', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('fecha_baja', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('fecha_actualizacion', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('kilometraje', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('id_conductor', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id_conductor'], ['conductores.id'], name='vehiculos_id_conductor_fkey'),
    sa.PrimaryKeyConstraint('id', name='vehiculos_pkey')
    )
    op.create_index('ix_vehiculos_patente', 'vehiculos', ['patente'], unique=True)
    op.create_index('ix_vehiculos_modelo', 'vehiculos', ['modelo'], unique=False)
    op.create_index('ix_vehiculos_marca', 'vehiculos', ['marca'], unique=False)
    op.create_index('ix_vehiculos_id', 'vehiculos', ['id'], unique=False)
    op.create_index('ix_vehiculos_codigo', 'vehiculos', ['codigo'], unique=True)
    # ### end Alembic commands ###
