"""Crear tabla conductores

Revision ID: 938bc63d86be
Revises: 
Create Date: 2025-03-02 17:00:29.936208

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '938bc63d86be'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_conductores_id', table_name='conductores')
    op.drop_table('conductores')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conductores',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('apellido', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('dni', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('numero_licencia', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('numero_contacto', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('email_contacto', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('fecha_vencimiento_licencia', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('direccion', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('creado_en', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('actualizado_en', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='conductores_pkey'),
    sa.UniqueConstraint('dni', name='conductores_dni_key')
    )
    op.create_index('ix_conductores_id', 'conductores', ['id'], unique=False)
    # ### end Alembic commands ###
